version: "3.5"
services:
  api:
    container_name: api
    hostname: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    expose:
      - "2391"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"
